// KaTeX macro definitions shared between pages
const katexMacros = {
    "\\Ker": "\\operatorname{Ker}",
    "\\Ima": "\\operatorname{Im}",
    "\\Hom": "\\operatorname{Hom}",
    "\\End": "\\operatorname{End}",
    "\\Aut": "\\operatorname{Aut}",
    "\\Mor": "\\operatorname{Mor}",
    "\\Ob": "\\operatorname{Ob}",
    "\\id": "\\operatorname{id}",
    "\\Spec": "\\operatorname{Spec}",
    "\\Proj": "\\operatorname{Proj}",
    "\\Sing": "\\operatorname{Sing}",
    "\\Smooth": "\\operatorname{Smooth}",
    "\\Normal": "\\operatorname{Normal}",
    "\\Ann": "\\operatorname{Ann}",
    "\\tr": "\\operatorname{tr}",
    "\\rk": "\\operatorname{rk}",
    "\\GL": "\\operatorname{GL}",
    "\\SL": "\\operatorname{SL}",
    "\\SO": "\\operatorname{SO}",
    "\\Sp": "\\operatorname{Sp}",
    "\\PSL": "\\operatorname{PSL}",
    "\\GF": "\\operatorname{GF}",
    "\\R": "\\mathbb{R}",
    "\\C": "\\mathbb{C}",
    "\\Z": "\\mathbb{Z}",
    "\\Q": "\\mathbb{Q}",
    "\\N": "\\mathbb{N}",
    "\\F": "\\mathbb{F}"
};
